version: '3.8'

services:
  bot:
    build: .
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_URL=redis://redis:6379
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - BSC_RPC_URL=${BSC_RPC_URL}
      - POLYGON_RPC_URL=${POLYGON_RPC_URL}
      - AVALANCHE_RPC_URL=${AVALANCHE_RPC_URL}
      - ARBITRUM_RPC_URL=${ARBITRUM_RPC_URL}
      - OPTIMISM_RPC_URL=${OPTIMISM_RPC_URL}
      - FANTOM_RPC_URL=${FANTOM_RPC_URL}
      - PULSECHAIN_RPC_URL=${PULSECHAIN_RPC_URL}
      - PI_RPC_URL=${PI_RPC_URL}
      - DOGE_RPC_URL=${DOGE_RPC_URL}
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - NEAR_RPC_URL=${NEAR_RPC_URL}
      - TRON_RPC_URL=${TRON_RPC_URL}
      - ALGORAND_RPC_URL=${ALGORAND_RPC_URL}
      - TON_RPC_URL=${TON_RPC_URL}
      - POLKADOT_RPC_URL=${POLKADOT_RPC_URL}
      - BASE_RPC_URL=${BASE_RPC_URL}
      - COSMOS_RPC_URL=${COSMOS_RPC_URL}
      - EOS_RPC_URL=${EOS_RPC_URL}
      - OSMOSIS_RPC_URL=${OSMOSIS_RPC_URL}
    depends_on:
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: